version: "3" 
services:
  go-chatgpt-api:
    container_name: go-chatgpt-api
    image: linweiyuan/go-chatgpt-api
    ports:
      - 8080:8080         # 容器端口映射到宿主机8080端口；宿主机监听端口可按需改为其它端口
    #network_mode: host   # 可选，将容器加入主机网络模式，即与主机共享网络命名空间；上面的端口映射将失效
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
      - GO_CHATGPT_API_PROXY=http://127.0.0.1:7890      # GO_CHATGPT_API_PROXY=：科学上网代理地址，例如：http://127.0.0.1:7890；可留空
      - GO_CHATGPT_API_ARKOSE_TOKEN_URL=http://chatgpt-arkose-token-api:65526
      #- GO_CHATGPT_API_PROXY=socks5://chatgpt-proxy-server-warp:65535  # IP被Ban，提示Access denied之类的报错，可尝试使用warp，把注释取消
    depends_on:
      - chatgpt-arkose-token-api
    restart: unless-stopped

  chatgpt-arkose-token-api:
    container_name: chatgpt-arkose-token-api
    image: linweiyuan/chatgpt-arkose-token-api
    restart: unless-stopped

# IP被Ban，提示Access denied之类的报错，可尝试使用warp，把注释取消
  #chatgpt-proxy-server-warp:
  #  container_name: chatgpt-proxy-server-warp
  #  image: linweiyuan/chatgpt-proxy-server-warp
  #  environment:
  #    - LOG_LEVEL=OFF
  #  restart: unless-stopped
